name: Processar Playlist

on:
  repository_dispatch:
    types: [nova_playlist]

jobs:
  processar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - run: pip install yt-dlp mutagen google-auth google-api-python-client requests
      - name: Correr o script de processamento
        run: |
          python worker.py "${{ github.event.client_payload.drive_folder_link }}" "${{ github.event.client_payload.playlist_link }}" "${{ github.event.client_payload.google_access_token }}"
